version: '2.4'

networks:
  kanban:
    ipam:
      driver: default
      config:
        - subnet: "172.90.0.0/24"

services:
  kanban_api:
    image: kanban_api:latest
    ports:
      - "5000:80"
    expose:
      - "5000"
    volumes:
      - ./:/opt/command
    mem_limit: 1GB
    command: ["dotnet", "kanban-api.dll"]
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      kanban:
        aliases:
          - kanban_api
      
  front:
    image: kanban_frontend:latest
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./:/opt/command
    working_dir: /opt/app
    command: ["yarn", "start"]
    networks:
      kanban:
        aliases:
          - kanban_front 
